/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_theveganrobot_cmake_HelloBoost */

#ifndef _Included_com_theveganrobot_cmake_HelloBoost
#define _Included_com_theveganrobot_cmake_HelloBoost
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_theveganrobot_cmake_HelloBoost
 * Method:    boostMkDir
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_theveganrobot_cmake_HelloBoost_boostMkDir
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
