/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_theveganrobot_cmake_HelloWorld */

#ifndef _Included_com_theveganrobot_cmake_HelloWorld
#define _Included_com_theveganrobot_cmake_HelloWorld
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_theveganrobot_cmake_HelloWorld
 * Method:    stringFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_theveganrobot_cmake_HelloWorld_stringFromJNI
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
