/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_theveganrobot_cmake_HelloEigen */

#ifndef _Included_com_theveganrobot_cmake_HelloEigen
#define _Included_com_theveganrobot_cmake_HelloEigen
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_theveganrobot_cmake_HelloEigen
 * Method:    helloMatrix
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_theveganrobot_cmake_HelloEigen_helloMatrix
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
